src/types.rs
Error variant `Api::Problem` prints "API error: {problem}" however the Problem struct has display impl that starts by printing "API error". Together this results in "API error: API error" followed by the details.
This fixes that by annotating `Api::Problem` with `thiserror`'s `transparent` attribute which forwards the display impl to the underlying types display impl.
=> Annotate Api::Problem error with thiserror::transparent

src/lib.rs
Lets encrypt can return a clear error when creating a new order without returning an `order_url`. 
A missing `order_url` however triggers an early return with error message `no order URL found`. The error from lets encrypt is then never shown to the crate user.
Swapping the `state` and `url` field instantiation in `new_order`  is enough to let `Problem::check` emit the lets encrypt error.
Requesting a certificate for *example.org*:
Original output:
```
missing data: no order URL found
```
New:
```
API error: Error creating new order :: Cannot issue for "example.org": The ACME server refuses to issue a certificate for this domain name, because it is forbidden by policy (urn:ietf:params:acme:error:rejectedIdentifier)
```
=> emit Problem::check error even if no url found

src/lib.rs
See PR #17 for the original issue
edit: worked on the wrong branch and then pressed PR so it took a rebase to get this to merge cleanly. Which is why the force-push is there
=> Add comment to prevent swapping fields causing wrong early return 

Cargo.toml, src/lib.rs
@surban @dvdsk I think I'd prefer to keep this simple -- it seems very unlikely to me that anyone started using instant-acme 0.3.1 with a non-`Send + Sync + 'static` client in the past 2 days. Does this work for your use cases?
Fixes #25. Alternative to #26.
=> Add some bounds for HttpClient trait

src/lib.rs
Re: [this](https://github.com/instant-labs/instant-acme/issues/23#issuecomment-1586801208), turns out adding an associated type to `HttpClient` would break the trait objectivity. So instead, more `Box<dyn>`!
=> Replace `ResponseFuture` with `Box<dyn>`

src/lib.rs
It seems during refactoring code related to https://github.com/instant-labs/instant-acme/pull/28 the Send trait was missed, causing compilation errors in certain scenarios such as the following sample:
```rust
use instant_acme::{Account, NewAccount};
#[tokio::main]
async fn main() {
tokio::spawn(
async move{
let account: Account = Account::create(
&NewAccount {
contact: todo!(),
terms_of_service_agreed: true,
only_return_existing: false,
},
"directory",
None
)
.await.unwrap();
let mut order = account
.new_order(&instant_acme::NewOrder {
identifiers: todo!(),
})
.await;
}
).await;
}
```
Error:
```
error: future cannot be sent between threads safely
--> src\main.rs:6:9
|
6   | /         async move{
7   | |             let account: Account = Account::create(
8   | | …
```
=> Adding Send trait to HttpClient response due to rust's threads safety compilation error

Cargo.toml, examples/provision.rs, src/lib.rs, src/types.rs
Only yield `AccountCredentials` (which gives access to the private key) at `Account` creation time. Store the `directory` in the `AccountCredentials` and prefer using it to acquire new `DirectoryUrls` if available at deserialization time.
=> Improve credential handling

Cargo.toml, src/lib.rs, src/types.rs
Adds certificate revocation, though I'm not entirely sure if the impl should be located in the types.rs.
=> Add certificate revocation

Cargo.toml, src/types.rs
Alternative to #43. RFC 8555 says in [section 8](https://datatracker.ietf.org/doc/html/rfc8555#section-8):
> * error (optional, object):  Error that occurred while the server was validating the challenge, if any, structured as a problem document [[RFC7807](https://datatracker.ietf.org/doc/html/rfc7807)].  Multiple errors can be indicated by using subproblems [Section 6.7.1](https://datatracker.ietf.org/doc/html/rfc8555#section-6.7.1).  A challenge object with an error MUST have status equal to "invalid".
RFC 7807 in [section 3.1](https://datatracker.ietf.org/doc/html/rfc7807#section-3.1) isn't very structured about describing optionality, but it has the following bits of context (emphasis mine):
> * "type" (string) - A URI reference …
=> Make Problem fields optional

.github/workflows/rust.yml, Cargo.toml, examples/provision.rs, src/lib.rs, src/types.rs
This PR adds the aws_lc_rs feature to the instant-acme library, sets it as the default feature, and updates the dependencies.
=> Add aws_lc_rs feature and set it as default

.github/workflows/rust.yml, Cargo.toml, README.md, src/lib.rs, src/types.rs
* Followup from #56 to clean things up a bit
* Cleanup from #50 
* Restore ability to build `HttpClient` implementations without hyper (after #50)
* Incorporate #54 (fixes #51)
=> Prepare 0.7.0 release

src/lib.rs
I'm putting this up as a possible solution for handling bad nonce errors. The new `BytesBody` implementation feels a bit weird but I couldn't think of a better way that wouldn't have wide reaching interface changes. I think it makes sense to do the retry within `Client` so that everything benefits from it. The main thing this is missing is some backoff, though that may not even be necessary because we're not retrying due to a network or server side error.
Fixes: https://github.com/djc/instant-acme/issues/62
=> Retry bad nonce errors with a new nonce

src/lib.rs
This PR adds `pub fn id()` to Account. The account id is used when we need to add the account to [CAA](https://letsencrypt.org/docs/caa/) records.
=> Add `pub fn id()` to Account

src/lib.rs
Fixes #72 by adding a clarifying note to the documentation.
=> Clarify documentation on external account key encoding

README.md
* Update MSRV and include the acronym for easier CTRL-F'ing.
* Remove challenge type testing limitation. I'm confident in the other challenge types being RFC 8555 compatible.
* Clarify the key type limitation: firstly that it's specific to account keys (not certificates issued with the account) and secondly that it's only the P-256 ECDSA curve supported.
=> README: small tweaks

deny.toml
Let's start here to keep CI passing? And wait for the debris from the advisory to clear...
=> Ignore unmaintained *ring* advisory for now

src/types.rs, tests/pebble.rs
When an ACME CA rejects an order submitted by a client it's helpful to be able to indicate _which_ of the order's identifiers are at fault and why. [RFC 8555 §6.7.1](https://www.rfc-editor.org/rfc/rfc8555#section-6.7.1) describes how subproblems within a top-level problem are used for this purpose.
This branch implements support for capturing and rendering problem information containing subproblems based on §6.7.1. Pebble implemented returning subproblems for the case where an identifier in an order is rejected on the basis of CA policy  (https://github.com/letsencrypt/pebble/pull/383). We use this implementation to add a new integration test exercising a problem-with-subproblems response from the test CA.
=> Implement RFC 8555 §6.7.1 subproblems

examples/provision.rs, tests/pebble.rs
Previously both the provision example and the Pebble integration test logic created a new order for a set of input identifiers, iterated the authorizations for the resulting order, and then pulled out the identifier/challenge for each **pending** status authz. After POSTing each authz's challenge URL the associated challenge identifiers were used for the CSR sent to finalize the order.
Since the logic above only processes pending authz's it would skip any that are already **valid** (e.g. from previous orders). This can end up producing a CSR that has fewer names than the initial order, which provokes an error during finalization when the CA rejects the CSR.
The solution is simple: don't tie the CSR identifiers to the challenges at all, use the same list of identifiers as was used to …
=> Fix authorization reuse in provision.rs and the Pebble integration tests

.github/workflows/pebble.yml, Cargo.toml, README.md, examples/provision.rs, src/lib.rs, src/types.rs, tests/pebble.rs
This branch implements [ACME Renewal Information](https://www.ietf.org/archive/id/draft-ietf-acme-ari-08.html) based on `draft-08`. While not yet a proposed standard RFC this draft is nearly at that stage, and has been [deployed by Let's Encrypt](https://letsencrypt.org/2023/03/23/improving-resliiency-and-reliability-with-ari/) (and I believe Google as well).
Support brings a few new bits of API surface:
* a new `CertificateIdentifier` type that uniquely identifies a certificate for ARI compatible servers. This requires parsing specific certificate fields to construct, and so without taking a dependency users are expected to provide the relevant `pki_types::Der` data pre-extracted from a certificate.
* for users willing to take an optional `x509-parser` dependency we offer a way to go …
=> Implement ACME Renewal Information (ARI)

.github/workflows/pebble.yml, examples/provision.rs, src/lib.rs, src/types.rs, tests/pebble.rs
Add support for deactivating authorizations, and ACME accounts. 
Additionally add a wildcard identifier to the DNS-01 integration test and fix the issued certificate validation logic to support this.
=> Add authorization and account deactivation

src/lib.rs
The spec says this is a MUST. We temporarily relaxed this requirement while Let's Encrypt fixed a bug with their server-side ARI implementation. Since that bug was fixed, we can go back to matching what the spec says.
I tested this works as expected with both LE's staging & prod ACME servers. Pebble was already doing the right thing, so no test diff is required.
Follow-up from https://github.com/djc/instant-acme/pull/85
=> lib: enforce ARI order state includes replaces

src/types.rs, tests/pebble.rs
While [Let's Encrypt has announced upcoming support](https://letsencrypt.org/2025/01/16/6-day-and-ip-certs/#ip-address-support-for-securing-additional-use-cases) for issuing certificates for IP address subjects, it isn't available yet.
Fortunately, Pebble does support this, so we can implement the feature now and have it ready for Let's Encrypt's staging and production environments.
See [RFC 8738](https://www.rfc-editor.org/rfc/rfc8738).
=> Add RFC 8738 IP address identifiers

src/lib.rs
This pull requests improves api error reporting for challenge set_ready.
If an ACME server provides error information on the HTTP layer as a RFC 8707 probem details document, this error information is provided to the caller of the set_ready method as Error::Api(...). But if an ACME server provides the error information as part of the Challenge object (error member, RFC8555 section 8) the current implementation does not forward this information to the caller of set_ready as an Err(Error::Api(...)). This is changed in this pull request.
=> probem details from challenge object

README.md, src/lib.rs, src/types.rs, tests/pebble.rs
This pull request adds account features and one fix to the instant-acme client:
- A new feature is added to update the contact information of an existing acme account
- A new feature is added to perform an account key rollover of an existing acme account
The contact information that is part of the acme account is according to RFC 8555, section 7.3.2. The contact update payload includes a the contact information as for example an email address.
The account key rollover is according to RFC 8555, section 7.3.5. New credentials are created by the instant-acme client and updated on the acme server. The new credentials are returned to the caller for further usage.
=> Acme account features

src/lib.rs
Inspired by #101. I don't think there are any other places where it makes sense to yield from the `Order` or `Challenge` `error` fields.
=> Yield error state from Order::poll() if set

.github/workflows/pebble.yml
Previously our CI needed [a fix that was merged to Pebble main](https://github.com/letsencrypt/pebble/commit/dc9bf9d200b49f5b587258ec53948f17417a7579), but not yet released, so we switched to building it from source.
There's since been a [v2.8.0](https://github.com/letsencrypt/pebble/releases/tag/v2.8.0) release that includes the required fix so we can switch back to using pre-built release binaries.
=> ci: switch back to pre-built Pebble

README.md, src/account.rs, src/types.rs
Hot off the press, ARI is now a proposed internet standard with an RFC number: https://www.rfc-editor.org/rfc/rfc9773.html
This commit updates all of the pre-existing references to the draft spec in various comments to use the finalized RFC. AFAICT, no sections were renumbered.
=> docs: update ARI draft refs to RFC 9773

examples/provision.rs, src/lib.rs, src/order.rs, tests/pebble.rs
This type can be constructed and updated in a const context and is mostly opaque so we can evolve what the exact policy looks like without API changes.
=> Encapsulate retry policy in a type

examples/provision.rs, src/account.rs, src/lib.rs, src/types.rs, tests/pebble.rs
To avoid combinatorial explosion of constructors.
Preparation for #94.
=> Use builder pattern for Account creation

Cargo.lock, Cargo.toml, src/account.rs, src/order.rs
As discussed in #104, Pebble doesn't support this so it's untested for now.
cc @christianhoelzl
=> Add support for Retry-After headers in poll()

src/account.rs, src/lib.rs, src/types.rs, tests/pebble.rs
Obsoletes #94, fixes #93.
cc @axos88
=> Add support for loading existing accounts from key

examples/provision.rs, src/order.rs, tests/pebble.rs
This pull request adds a new function to poll a certificate. In contrast to the existing `Order::certificate` function, this method retries in case of a `Processing` state based on the retry policy. 
Pebble testing is modified such that it uses the new method `Order::poll_certificate`. This removes a `loop` from the test function `Environment::certificate`.
I can add commits to this pr if wanted:
- rename `Order::poll` to `Order::poll_ready`
- remove public from `Order::certificate`
=> poll certificate function

src/account.rs, src/lib.rs, src/order.rs, tests/pebble.rs
This pull request adds an extension to the function `Account::renewal_info()` to additionally yield the Retry-After header as a `SystemTime`. Reference is [RFC 9773, 4.3.2 Client Handling of Retry-After](https://www.rfc-editor.org/rfc/rfc9773.html#section-4.3.2). The `SystemTime` is a hint from the ACME server when to again fetch the renewal window.
=> extend renewal_info() to yield retry-after header

.github/workflows/rust.yml, Cargo.toml
The external types situation isn't great ATM (mostly due to the `HttpClient` trait, and the `Error` enum) but we can at least prevent backsliding with a CI check while considering improvements to reduce the number of blessed deps.
=> ci: add external types and semver compat checks

examples/provision.rs, src/types.rs
The 0.8 release contains substantial changes to make the API more modular. It integrates full support for ACME Renewal Information (ARI, recently standardized as RFC 9773).
* Add support for the ACME profiles extension draft (see #98).
* Add support for the ACME renewal information extension (see #85).
* Add support for IP address identifiers (#97).
* Use a builder setup to build accounts via `Account::builder()` or `Account::builder_with_http()` (see #110).
* `NewOrder` values must be created through a builder as well (via `NewOrder::new()`).
* Authorizations can now be accessed via a stream-like API available through `Order::authorizations()` (see #92).
* Integrated API to poll order readiness and certificate, with configurable retry policy (see #108, #121).
When upgrading, consider …
=> Prepare 0.8 release

src/types.rs
Continuation of https://github.com/djc/instant-acme/pull/136
=> types: don't serialize a null NewOrder.profiles field

Cargo.lock, Cargo.toml, examples/certgen.rs
- Avoid encoding `replacing: null` in new order requests for ZeroSSL compatibility (see #136).
For #136.
=> Prepare 0.8.1

src/account.rs, src/lib.rs
Fixes https://github.com/djc/instant-acme/issues/144
Note that this PR also renames the `req` variable to `request` in `Client::new` for consistency.
Perhaps the user agent could be made to be configurable externally, however I see no real need for that.
=> Add `USER_AGENT` header to requests

deny.toml
IMO this is a good default, and I've been using instant-acme as my Rust template repository of choice...
=> Fail CI on yanked dependencies

Cargo.lock, Cargo.toml
Expose `AccountCredentials::private_key()` getter and clarify supported key types.
=> Bump version to 0.8.3
